[
    {   all_id:'河北省',
        shrz_title:'查询详细',
        shrz_content:'查询详细',
        asker:'查询详细',
        replier:'查询详细',
        shrz_createtime:'查询详细',
        uiProvider:'col',
        children:[{
            all_id:'河北省郑州市',
            shrz_title:'查询详细',
            shrz_content:'查询详细',
            asker:'查询详细',
            replier:'查询详细',
            shrz_createtime:'查询详细',
            uiProvider:'col',
            cls:'master-task',
            iconCls:'task-folder',
             leaf:false,
            children:[{
                all_id:'河北省郑州市XX区',
                shrz_title:'查询详细',
                shrz_content:'查询详细',
                asker:'查询详细',
                replier:'查询详细',
                shrz_createtime:'查询详细',
                uiProvider:'col',
                cls:'master-task',
                 leaf:true,
                iconCls:'task-folder'
            }]
        },{
            all_id:'查询',
            shrz_title:'查询详细',
            shrz_content:'查询详细',
            asker:'查询详细',
            replier:'查询详细',
            shrz_createtime:'查询详细',
            uiProvider:'col',
            cls:'master-task',
            iconCls:'task-folder',
            leaf:true
            }
        ]
    }
]

