[
    {   zonename:'江苏省南京市江浦县',
        zonecode:'320122',
        mNum:'0',
        mtreadNum:'0',
        mNtreadNum:'0',
        yNum:'0',
        ytreadNum:'0',
        yNtreadNum:'0',
        uiProvider:'col',
        expanded: true,
        children:[{
            zonename:'江苏省南京市江浦县',
            zonecode:'320122',
            mNum:'0',
            mtreadNum:'0',
            mNtreadNum:'0',
            yNum:'0',
            ytreadNum:'0',
            yNtreadNum:'0',
            uiProvider:'col',
            cls:'master-task',
            iconCls:'task-folder',
             leaf:false,
//            expanded: true,
            children:[{
                zonename:'江苏省南京市江浦县',
                zonecode:'320122',
                mNum:'0',
                mtreadNum:'0',
                mNtreadNum:'0',
                yNum:'0',
                ytreadNum:'0',
                yNtreadNum:'0',
                uiProvider:'col',
                cls:'master-task',
                 leaf:false,
                iconCls:'task-folder'   ,
                children:[{
                    zonename:'江苏省南京市江浦县',
                    zonecode:'320122',
                    mNum:'0',
                    mtreadNum:'0',
                    mNtreadNum:'0',
                    yNum:'0',
                    ytreadNum:'0',
                    yNtreadNum:'0',
                    uiProvider:'col',
                    cls:'master-task',
                    leaf:true,
                    color:"red",
                    iconCls:'task-folder'
                }]
            }]
        },{
            zonename:'江苏省南京市江浦县',
            zonecode:'320122',
            mNum:'0',
            mtreadNum:'0',
            mNtreadNum:'0',
            yNum:'0',
            ytreadNum:'0',
            yNtreadNum:'0',
            uiProvider:'col',
            cls:'master-task',
            iconCls:'task-folder',
            leaf:true
            }
        ]
    }
]

